version: 2.1

executors:
  default:
    working_directory: ~/webapp/src
    docker:
      - image: circleci/php:7.4-cli  # PHPのテスト用イメージを指定
        environment:
          RAILS_ENV: test
          DB_HOST: test_db            # テスト用DBホストをtest_dbに変更
          DB_USERNAME: test_user      # test_dbで設定したユーザー名
          DB_PASSWORD: ''             # 空パスワードを指定
      - image: mysql:8.0.26
        name: test_db
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: ''

commands:
  setup:
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: composer install

      - run:
          name: Wait for test_db
          command: dockerize -wait tcp://test_db:3306 -timeout 90s

      - run:
          name: Database setup
          command: |
            php artisan migrate --env=testing --force
            php artisan db:seed --env=testing --force

jobs:
  test:
    executor: default
    steps:
      - setup

      - run:
          name: Run PHPUnit tests
          command: ./vendor/bin/phpunit

workflows:
  build_and_test:
    jobs:
      - test