version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.1-node
      - image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass

    working_directory: ~/laravel-project

    steps:
      - checkout

      - run:
          name: Install Docker Compose v2
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      - run:
          name: Install dockerize
          command: |
            sudo curl -L https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz | sudo tar -C /usr/local/bin -xzv

      - run:
          name: Start services with Docker Compose
          command: docker-compose up -d

      - run:
          name: Wait for MySQL test_db to be ready
          command: |
            dockerize -wait tcp://test_db:3306 -timeout 1m

      - run:
          name: Install dependencies with Composer
          command: composer install

      - run:
          name: Run Laravel migrations for testing
          command: php artisan migrate --env=testing --force

      - run:
          name: Run PHPUnit tests
          command: php artisan test